name: Health Check

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: diamondburned/libwebring/.github/actions/health-check@v0.2.0
        with:
          webring-input: webring.json
          commit: true
          commit-message: "Update webring status"
